language: node_js
node_js:
    - "6.9"
    - "6.10"
    - "7.6"
before_install:
    - "export CHROME_BIN=chromium-browser"
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
before_script:
    # Excludes gecko, see: https://github.com/angular/webdriver-manager/issues/216#issuecomment-293650564
    - "npm run webdriverUpdate -- --gecko false"
