// Generated by CoffeeScript 1.12.4
(function() {
  var path;

  path = require('path');

  module.exports.config = {
    framework: 'custom',
    frameworkPath: require.resolve('@darrinholst/protractor-cucumber-framework'),
    capabilities: {
      'chromeOptions': {
        args: ['--test-type']
      }
    },
    cucumberOpts: {
      require: [
        path.resolve('./node_modules/cukefarm/lib/step_definitions/GeneralStepDefs'),
        path.resolve('./node_modules/cukefarm/lib/step_definitions/Transform')
      ],
      format: 'pretty'
    },
    onPrepare: function() {
      browser.ignoreSynchronization = true;
      browser.manage().timeouts().setScriptTimeout(5000);
      return browser.manage().timeouts().implicitlyWait(5000);
    }
  };

}).call(this);
