// Generated by CoffeeScript 1.12.4
(function() {
  var ElementHelper, World, chai, chaiAsPromised, expect;

  chai = require('chai');

  chaiAsPromised = require('chai-as-promised');

  chai.use(chaiAsPromised);

  expect = chai.expect;

  ElementHelper = require('../lib/support/ElementHelper.js');

  World = require('../lib/support/World.js').World;

  describe('elementHelper', function() {
    var elementHelper;
    elementHelper = new ElementHelper();
    before(function() {
      browser.get('http://localhost:9001/');
      return browser.manage().timeouts().implicitlyWait(100);
    });
    it('should exist on the World', function() {
      var world;
      world = new World(function() {});
      return expect(world.elementHelper).to.be.an.instanceOf(ElementHelper);
    });
    return describe('hasClass()', function() {
      afterEach(function() {
        browser.driver.switchTo().defaultContent();
        return browser.driver.executeScript("fixtures.cleanUp();");
      });
      it('should return true if the element has the given class', function() {
        var el;
        browser.driver.executeScript("fixtures.set('<input id=\"testCheckbox\" class=\"test-class\"/>');");
        browser.driver.switchTo().frame('js-fixtures');
        el = $('input#testCheckbox');
        return expect(elementHelper.hasClass(el, 'test-class')).to.eventually.equal(true);
      });
      it('should return false if the element does not have the given class', function() {
        var el;
        browser.driver.executeScript("fixtures.set('<input id=\"testCheckbox\" class=\"test-class\"/>');");
        browser.driver.switchTo().frame('js-fixtures');
        el = $('input#testCheckbox');
        return expect(elementHelper.hasClass(el, 'fake-class')).to.eventually.equal(false);
      });
      return it('should return false if the element has no class', function() {
        var el;
        browser.driver.executeScript("fixtures.set('<input id=\"testCheckbox\"/>');");
        browser.driver.switchTo().frame('js-fixtures');
        el = $('input#testCheckbox');
        return expect(elementHelper.hasClass(el, 'missing-class')).to.eventually.equal(false);
      });
    });
  });

}).call(this);
